# -*- coding: utf-8 -*-
"""parte1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vn9tq-1MEvpJks2XlWa0ZJB6gtCvRqNh
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# ===============================================
# 1. CARGA DE DATOS
# ===============================================
df = pd.read_csv("unificado.csv")

# ===============================================
# 2. LIMPIEZA Y PREPARACIÓN DE DATOS
# ===============================================
# Reemplazar los valores 999 y 9999 por NaN ya que suelen representar valores perdidos
df.replace({999: np.nan, 9999: np.nan}, inplace=True)

# Separar las variables numéricas y categóricas
numericas = df.select_dtypes(include=[np.number])
categoricas = df.select_dtypes(exclude=[np.number])

# ===============================================
# 3. ANÁLISIS DESCRIPTIVO DE VARIABLES NUMÉRICAS
# ===============================================
# Calcular estadísticas como media, desviación estándar, min, max, etc.
desc_stats = numericas.describe().T

# Agregar medidas de forma de la distribución
desc_stats["skewness"] = numericas.skew()      # Asimetría
desc_stats["kurtosis"] = numericas.kurtosis()  # Curtosis

# Mostrar resumen estadístico completo
display(desc_stats)

# ===============================================
# 4. VISUALIZACIÓN: HISTOGRAMAS Y BOXPLOTS
# ===============================================
# Crear histogramas y diagramas de caja para cada variable numérica
for col in numericas.columns:
    plt.figure(figsize=(14, 5))

    # Histograma con curva de densidad
    plt.subplot(1, 2, 1)
    sns.histplot(numericas[col].dropna(), kde=True, bins=30)
    plt.title(f"Histograma: {col}")

    # Diagrama de caja (boxplot) para ver outliers
    plt.subplot(1, 2, 2)
    sns.boxplot(x=numericas[col])
    plt.title(f"Boxplot: {col}")

    plt.tight_layout()
    plt.show()

# ===============================================
# 5. MATRIZ DE CORRELACIÓN ENTRE VARIABLES NUMÉRICAS
# ===============================================
# Visualizar cómo se relacionan las variables entre sí
plt.figure(figsize=(12, 8))
sns.heatmap(numericas.corr(), annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Matriz de correlación")
plt.show()

# ===============================================
# 6. TRATAMIENTO DE VALORES FALTANTES
# ===============================================
# Imputar valores faltantes usando la media de cada variable
imputer = SimpleImputer(strategy="mean")
numericas_imputadas = pd.DataFrame(imputer.fit_transform(numericas), columns=numericas.columns)

# ===============================================
# 7. DETECCIÓN DE OUTLIERS CON MÉTODO IQR
# ===============================================
outliers_info = {}
for col in numericas.columns:
    q1 = numericas[col].quantile(0.25)
    q3 = numericas[col].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    outliers = ((numericas[col] < lower) | (numericas[col] > upper)).sum()
    outliers_info[col] = outliers

# Mostrar cantidad de outliers por variable
df_outliers = pd.DataFrame.from_dict(outliers_info, orient='index', columns=['Outliers'])
display(df_outliers)

# ===============================
# RELACIONES ENTRE VARIABLES
# ===============================

print("📌 Análisis de relaciones entre variables numéricas:\n")
# Ya se visualizó la matriz de correlación, pero ahora se puede complementar con pares específicos:
top_corr = numericas.corr().unstack().sort_values(ascending=False)
top_corr = top_corr[(top_corr < 1) & (top_corr > 0.5)].drop_duplicates()
print("🔍 Pares de variables numéricas con alta correlación (> 0.5):")
display(top_corr)

# Relación entre edad y escolaridad
plt.figure(figsize=(6, 5))
sns.scatterplot(data=df, x="EDADHOM", y="ESCHOM", alpha=0.3)
plt.title("Relación entre Edad y Escolaridad (Hombres)")
plt.show()

plt.figure(figsize=(6, 5))
sns.scatterplot(data=df, x="EDADMUJ", y="ESCMUJ", alpha=0.3)
plt.title("Relación entre Edad y Escolaridad (Mujeres)")
plt.show()

# Cruce entre ocupación y escolaridad
print("📌 Distribución de escolaridad por ocupación del hombre:")
cross1 = pd.crosstab(df["CIUOHOM"], df["ESCHOM"])
display(cross1)

print("📌 Distribución de escolaridad por ocupación de la mujer:")
cross2 = pd.crosstab(df["CIUOMUJ"], df["ESCMUJ"])
display(cross2)

# Opcional: heatmap para visualizar cruce
plt.figure(figsize=(10, 6))
sns.heatmap(cross1, cmap="YlGnBu", cbar_kws={'label': 'Frecuencia'})
plt.title("Heatmap: Escolaridad vs Ocupación (Hombres)")
plt.ylabel("Ocupación (CIUOHOM)")
plt.xlabel("Escolaridad")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.heatmap(cross2, cmap="YlGnBu", cbar_kws={'label': 'Frecuencia'})
plt.title("Heatmap: Escolaridad vs Ocupación (Mujeres)")
plt.ylabel("Ocupación (CIUOMUJ)")
plt.xlabel("Escolaridad")
plt.tight_layout()
plt.show()


print(f"8. ANÁLISIS DE VARIABLES CATEGÓRICAS")

# ===============================================
# 8. ANÁLISIS DE VARIABLES CATEGÓRICAS
# ===============================================
# Para cada variable categórica:
# - Mostrar frecuencia absoluta
# - Mostrar proporciones relativas
# - Generar gráfico de barras
for col in categoricas.columns:
    print(f"\n🔸 {col} - Frecuencia absoluta:")
    display(df[col].value_counts(dropna=False).rename("Frecuencia").reset_index().rename(columns={"index": col}))

    print(f"\n🔸 {col} - Proporciones:")
    display(df[col].value_counts(normalize=True, dropna=False).rename("Proporción").reset_index().rename(columns={"index": col}))

    plt.figure(figsize=(8, 4))
    df[col].value_counts(dropna=False).plot(kind="bar", color="coral")
    plt.title(f"Gráfico de barras - {col}")
    plt.ylabel("Frecuencia")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

# ===============================================
# 9. ANÁLISIS DE AGRUPAMIENTO (CLUSTERING)
# ===============================================
# Estandarizar las variables numéricas
scaler = StandardScaler()
X_scaled = scaler.fit_transform(numericas_imputadas)

# Evaluar varios valores de k (número de clusters) usando silhouette score
silhouette_scores = []
for k in range(2, 10):
    kmeans = KMeans(n_clusters=k, random_state=42)
    labels = kmeans.fit_predict(X_scaled)
    score = silhouette_score(X_scaled, labels)
    silhouette_scores.append(score)

# Visualizar los scores para elegir mejor k
plt.figure(figsize=(8, 4))
plt.plot(range(2, 10), silhouette_scores, marker='o', color='purple')
plt.title("Silhouette Score vs Número de Clusters")
plt.xlabel("Clusters")
plt.ylabel("Silhouette Score")
plt.grid(True)
plt.show()

# Imprimir el mejor número de clusters encontrado
mejor_k = np.argmax(silhouette_scores) + 2
print(f"✅ Mejor número de clusters: {mejor_k}")